global:
  homebrew:
    brews:
      - "git"
      - "coreutils"
      - "k9s"
      - "fzf"
      - "ghq"
      - "chezmoi"
      - "mise"
      - "binutils"
      - "oh-my-posh"
      - "mas"
      - "nvim"
      - "trash"
      - "ripgrep"
      - "fish-shell/fish-beta-4/fish"
      - "glow"
      - "gh"
    casks:
      - "1password"
      - "1password-cli"
      - "visual-studio-code"
      - "font-caskaydia-mono-nerd-font"
      - "obsidian"
      - "powershell"
      - "ghostty"
      - "zed@preview"
    mas: []
    taps:
      - "fish-shell/fish-beta-4"
