global:
  homebrew:
    brews:
      - "git"
      - "coreutils"
      - "k9s"
      - "fzf"
      - "ghq"
      - "chezmoi"
      - "binutils"
      - "oh-my-posh"
      - "nvim"
      - "gh"
      - "jq"
      - "ripgrep"
      - "age"
      - "fd"
    casks:
      - "1password"
      - "1password-cli"
      - "visual-studio-code"
      - "font-caskaydia-mono-nerd-font"
      - "obsidian"
      - "powershell"
      - "ghostty@tip"
      - "zed@preview"
      - "zen"
      - "aerospace"
    mas: []
    taps:
      - "nikitabobko/tap"
