global:
  homebrew:
    brews:
    - "git"
    - "coreutils"
    - "k9s"
    - "fzf"
    - "ghq"
    - "chezmoi"
    - "mise"
    - "binutils"
    - "oh-my-posh"
    - "mas"
    - "nvim"
    - "trash"
    - "graphviz"
    casks:
    - "1password"
    - "1password-cli"
    - "amethyst"
    - "visual-studio-code"
    - "font-hack-nerd-font"
    - "obsidian"
    - "powershell"
    - "wezterm"
    mas: []
    taps:
    - "homebrew/cask-fonts"
