global:
  homebrew:
    brews:
      - "git"
      - "coreutils"
      - "k9s"
      - "fzf"
      - "ghq"
      - "chezmoi"
      - "mise"
      - "binutils"
      - "oh-my-posh"
      - "nvim"
      - "gh"
      - "jq"
    casks:
      - "1password"
      - "1password-cli"
      - "visual-studio-code"
      - "font-caskaydia-mono-nerd-font"
      - "obsidian"
      - "powershell"
      - "ghostty"
      - "zed@preview"
      - "zen-browser"
    mas: []
    taps: []
