global:
  homebrew:
    brews:
      - "git"
      - "coreutils"
      - "k9s"
      - "fzf"
      - "ghq"
      - "chezmoi"
      - "binutils"
      - "oh-my-posh"
      - "nvim"
      - "gh"
      - "jq"
      - "ripgrep"
      - "age"
      - "fd"
      - "tmux"
      - "tree-sitter-cli"
      - "btop"
      - "lazygit"
    casks:
      - "1password"
      - "1password-cli"
      - "visual-studio-code"
      - "font-caskaydia-mono-nerd-font"
      - "font-hurmit-nerd-font"
      - "obsidian"
      - "powershell"
      - "ghostty"
      - "zed@preview"
      - "zen"
      - "aerospace"
    mas: []
    taps:
      - "nikitabobko/tap"
  pacman:
    packages:
      - "age"
      - "binutils"
      - "chezmoi"
      - "coreutils"
      - "fd"
      - "fzf"
      - "git"
      - "github-cli"
      - "jq"
      - "k9s"
      - "neovim"
      - "obsidian"
      - "ripgrep"
      - "tmux"
      - "ttf-caskaydia-mono-nerd"
  aur:
    packages:
      - "ghq"
      - "tree-sitter-cli"
      - "ttf-hermit-nerd"
