{{- /* chezmoi:modify-template */ -}}

{{- $kubeconfig := list "~/.kube/config" -}}
{{- $mise := fromToml .chezmoi.stdin -}}

{{- if hasKey $mise "env" -}}
  {{- if hasKey $mise.env "KUBECONFIG" -}}
  {{- $kubeconfig = append $kubeconfig (split ":" $mise.env.KUBECONFIG) -}}
  {{- end -}}
{{- else -}}
{{- $_ := set $mise "env" dict -}}
{{- end -}}

{{- if has "personal" .profiles -}}
{{- $kubeconfig = append $kubeconfig "~/.kube/rasputin" -}}
{{- end -}}

{{ $mise | setValueAtPath "env.KUBECONFIG" ($kubeconfig | uniq | join ":") | toToml }}
